### ISSUE TITLE
Adding the plugins on next-plugins repo

### ISSUE THREAD

**Issue by prateekrastogi** [cyrilwanner/next-compose-plugins#1]
Hi,
The plugin you wrote feels like a must have feature while working with next.js plugins. Wouldn't it be beneficial for the community if you can add reference to this plugin in next.js plugins repo by creating a pull request? 
Literally, the first thought that comes to anyone mind after getting introduced with next plugins is how to compose multiple plugins with a cleaner api.

**Comment by cyrilwanner** [comment]
Hey @prateekrastogi, thank you for your feedback :)
I was not sure if I'm the only one who isn't happy with the standard way of composing next.js plugins, but I'll now create a PR for adding it the reference there.
