### ISSUE TITLE
use with ant-design

### ISSUE THREAD

**Issue by abhijithvijayan** [cyrilwanner/next-compose-plugins#19]
I need to use with a monorepo project that has `next/sass` & `next/css` already set up
the original example has this config https://github.com/zeit/next.js/blob/canary/examples/with-ant-design/next.config.js

my current config file is https://github.com/onepassapp/onepass/blob/master/packages/web/next.config.js

how do I use in the current file?

**Comment by abhijithvijayan** [comment]
Is it like 
![Screenshot from 2019-07-04 21-02-20](https://user-images.githubusercontent.com/34790378/60677424-1ae95a00-9e9f-11e9-8079-132148b97925.png)

this?

**Comment by jzhu1224** [comment]
```javascript
module.exports = withPlugins(
  [
    withCSS,
    withLess
    ]
  ],
  {
    webpack: (config, options) => {
      /** custom code */
  }
);
```

**Comment by abhijithvijayan** [comment]
@jzhu1224 Does it really matter if I don't include Less in the project as I use Sass already.
