### ISSUE TITLE
Add types for Typescript imports

### ISSUE THREAD

**Issue by TranquilMarmot** [cyrilwanner/next-compose-plugins#27]
When doing i.e.

```tsx
import MyImage from './myimage.png';
```

The Typescript compiler will complain.

The `next-images` project solves this by bundling a types declaration file: https://github.com/twopluszero/next-images/blob/master/index.d.ts

And then suggesting that you add a reference in `next-env.d.ts`: https://github.com/twopluszero/next-images#typescript

**Comment by cyrilwanner** [comment]
Hi @TranquilMarmot 
This is the wrong repository, you probably wanted to create it in `next-optimize-images`, so I'll close it here. And for `next-optimized-images`: this is planned to be shipped with the next version.
